config/routes.rb
InstunRails3::Application.routes.draw do

  match '/timetables/timetable_for_user/:id' => 'timetables#timetable_for_user', :via => [:get]
  resources :timetables do
    collection do
      get 'destroy/:id', action: :destroy
    end
    member do
      get 'list'
    end
  end

  resources :session_code do
    collection do
      get "new_popup"
      post "create_popup"
    end
  end
  resources :permission do
    collection do
      get 'list'
    end
  end
  resources :favourite_places do
    collection do
      get 'list'
    end
  end
  match '/user_applications/akuan_sah_hadir'    => 'user_applications#akuan_sah_hadir', :via => [:get]
  match '/user_applications/akuan_tidak_hadir'  => 'user_applications#akuan_tidak_hadir', :via => [:get]
  match '/user_applications/tidak_hadir_wakil'  => 'user_applications#tidak_hadir_wakil', :via => [:get]
  match '/user_applications/exam_before/:id' => 'user_applications#exam_before', :via => [:get]
  match '/user_applications/exam_after/:id' => 'user_applications#exam_after', :via => [:get]
  match '/user_applications/tambah_update/:id' => 'user_applications#tambah_update', :via => [:put]
  match '/user_applications/tambah/:id' => 'user_applications#tambah', :via => [:put]
  match '/user_applications/show_attendance/:id' => 'user_applications#show_attendance', :via => [:get]

  resources :user_applications do
    collection do
      get 'applied'
      get 'offered'
      get 'surat_tawaran'
      get 'attend'
      get 'history'
      get 'user_cancel/:id', :action => :user_cancel
      post 'sah_hadir_selected'
      post 'create_wakil'
    end
    member do
      put 'update_user_cancel'
      get 'print_offer_letter'
    end
  end
  resources :post_individus do
    collection do
      get 'list'
      get 'list_all'
    end
  end

  resources :post_courses do
    collection do
      get 'list'
      get 'list_all'
    end
  end

  resources :posts do
    collection do
      get 'list'
      get 'list_all'
    end
  end

  resources :job_profiles
  resources :religions
  resources :states
  resources :genders
  resources :races
  resources :marital_statuses
  resources :countries
  resources :relationships
  resources :cert_levels
  resources :titles
  resources :handicaps
  resources :permission
  resources :roles do
    collection do
      get 'list'
    end
  end
  resources :question_templates do
    collection do
      get 'list'
      post 'create_course'
      get 'new_course'
    end
  end
  resources :questions do
    collection do
      get 'list'
    end
  end
  resources :question_types do
    collection do
      get 'list'
    end
  end
  resources :question_sections do
    collection do
      get 'list'
    end
  end
  resources :scale_types do
    collection do
      get 'list'
    end
  end
  resources :scales do
    collection do
      get 'list'
    end
  end

  resources :hostel_statuses do
    collection do
      get 'list'
    end
  end
  resources :hostel_types do
    collection do
      get 'list'
    end
  end
  resources :hostel_policies do
    collection do
      get 'list'
    end
  end
  resources :hostel_fixtures do
    collection do
      get 'list'
    end
  end

  resources :facility_statuses do
    collection do
      get 'list'
    end
  end
  resources :facility_types do
    collection do
      get 'list'
    end
  end
  resources :facility_categories do
    collection do
      get 'list'
    end
  end

  resources :course_departments do
    collection do
      get 'list'
    end
  end
  resources :course_statuses do
    collection do
      get 'list'
    end
  end
  resources :course_fields do
    collection do
      get 'list'
      get 'new_popup'
      post 'create_popup'
    end
  end
  resources :course_locations do
    collection do
      get 'new_popup'
      post 'create_popup'
    end
  end
  resources :methodologies do
    collection do
      get 'list'
      get 'new_popup'
      post 'create_popup'
    end
  end

  resources :facilities do
    collection do
      get 'list'
      post 'createf'
    end
  end
  resources :facility_reservations do
    collection do
      get 'list'
    end
  end

  resources :places do
    collection do
      get 'list'
      get 'search'
      get 'list_kementerian'
      get 'list_pejabat'
      get 'new_kementerian'
      get 'new_pejabat'
      get 'create_kementerian'
      get 'create_pejabat'
      post 'search_by_name'
      post 'search_by_code'
      post 'search_by_phone'
      post 'search_by_state'
      get 'destroy/:id', action: :destroy
    end
    member do
      get 'show_kementerian'
      get 'edit_kementerian'
      put 'update_kementerian'
      put 'update_pejabat'
      get 'show_pejabat'
      get 'edit_pejabat'
      get 'destroy_kementerian'
      get 'destroy_pejabat'
    end
  end

  resources :signatures do
    get 'new_popup'
    get 'edit_popup'
    put 'update_popup'
    get 'show_popup'
    get 'destroy'
    collection do
      post 'create_popup'
      get 'list_popup'
      get 'new_popup'
    end
  end

  match '/trainer/:course_implementation_id/edit_surat_lantik_all' => 'trainer#edit_surat_lantik_all', :via => [:get]
  match '/trainer/:course_implementation_id/edit_surat_lantik' => 'trainer#edit_surat_lantik', :via => [:post]
  match '/trainer/:course_implementation_id/cetak_surat_lantik_all' => 'trainer#cetak_surat_lantik_all', :via => [:post]
  match '/trainer/:course_implementation_id/cetak_surat_lantik_all' => 'trainer#cetak_surat_lantik_all', :via => [:put]
  match '/trainer/:course_implementation_id/cetak_surat_lantik' => 'trainer#cetak_surat_lantik', :via => [:post]
  match '/trainer/:course_implementation_id/cetak_surat_lantik' => 'trainer#cetak_surat_lantik', :via => [:put]
  resources :trainer do
    get 'collect'
    get 'release'
    post 'offer'
    get 'offer'
    get 'eval'
    get 'destroy'
    collection do
      get 'offer_all'
      get 'list'
      get 'search'
      get 'claim_payment_index'
      post 'claim_payment_sent'
      post 'search_by_name'
      post 'search_by_ic'
      post 'search_by_phone'
      post 'search_by_expertise'
      post 'search_by_state'
      post 'offer'
    end
  end

  resources :finances do
    collection do
      get 'claim_payment_list'
      get 'search_claim_payment'
      post 'claim_payment_approve'
    end
  end

  resources :report_tables do
    collection do
      get 'general_achievement'
      get 'application_and_attendance'
      get 'peserta_jantina'
      get 'summary_group_ptg_ptd'
      get 'summary_group_jupem'
      get 'peserta_mengikut_jabatan'
      get 'trainer_by_department'
      get 'teach_hour_by_department'
      get 'students_feedback'
      get 'summary_group_jkptg'
      get 'payment_by_department'
      get 'trainer_average_score'
    end
  end

  resources :staffs do
    collection do
      get 'list'
      get 'search'
      post 'search_by_name'
      post 'search_by_phone'
      post 'search_by_dept'
      post 'new_but_staff_already_exist'
      post 'create_but_staff_already_exist'
    end
  end

  resources :report do
    collection do
      get 'list'
      get 'kursus_online'
      get 'kursus_semasa'
      get 'ringkasan_ujian'
    end
  end

  resources :laporan do
    collection do
      get 'audit_trail'
      get 'penilaian_penyelarasan'
      get 'list_laporan'
      get 'pencapaian_ujian_bidang'
      get 'mohon_espek'
      get 'statistik_kursus_tarikh'
      get 'pencapaian_ujian'
      get 'penilaian_penceramah'
      get 'penilaian_kemudahan'
      get 'penilaian_isi_kandungan'
      get 'senarai_ulasan'
      get 'kutipan_yuran'
      get 'kutipan_yuran_bhg'
      post 'sp_create'
      put 'sp_update'
    end
    member do
      get 'status_perlaksanaan'
    end
  end

  resources :reservations do
    collection do
      get 'list'
      get 'listp'
      get 'destroy/:id', action: :destroy
    end
    member do
      get 'new_popup'
      get 'edit_sah'
      get 'show_popup'
      get 'trainer_book'
      post 'trainer_book_create'
      get 'show_trainer_book'
      get 'edit_sah'
      post 'update_sah'
      get 'detail'
    end
  end

  resources :notifications do
    collection do
      get 'list'
      get 'report'
      get 'senaraibilik'
      get 'jadual_bilik_kuliah'
      get 'listp'
      get 'urushubung'
      post 'create_security_contact'
    end
    member do
      get 'detail'
      delete 'delete_security_contact'
      put 'approve'
    end
  end
  match '/hostels/list_sudah_checkin/:id' => 'hostels#list_sudah_checkin', :via => [:get]
  match '/hostels/iwannachkin/:id' => 'hostels#iwannachkin', :via => [:get]
  match '/hostels/showchkin/:id' => 'hostels#showchkin', :via => [:get]
  match '/hostels/:id/change_room' => 'hostels#change_room', :via => [:get]
  resources :hostels do
    collection do
      get 'list'
      get 'new_penghuni'
      post 'create_penghuni'
      get 'chkin_by_course'
      get 'find_checkout'
      get 'list_tutup'
      get 'find_guest'
      get 'rekod_guna_bilik'
      get 'blank'
      get 'lihat'
      get 'find_to_checkin'
      get 'list_active_course'
      get 'find_guest_result'
    end
    member do
      get 'iwannarent'
      get 'iverent'
      get 'showrent'
      get 'showchkin'
      get 'change_room_rent'
      get 'course_sankasha_ichiran'
      get 'cetak_list_checkin'
      get 'course_trainer_list'
      get 'iwannachkin'
      post 'ivedonechkin'
      get 'cetak_list_trainer_checkin'
    end
  end
  resources :quizzes do
    collection do
      get 'list'
      post 'hozon'
      get 'destroy/:id', action: :destroy
    end
    member do
      get 'shiken_ichiran'
      get 'shinki'
      get 'copy_shiken_ichiran'
      put 'simpan_copy_shiken_ichiran'
    end
  end

  match '/course_management/override_kelayakan/:id' => 'course_management#override_kelayakan', :via => [:post]

app/models/course_department.rb
# -*- encoding : utf-8 -*-
class CourseDepartment < ActiveRecord::Base
  has_many :course
  has_many :course_fields

	has_and_belongs_to_many :favourites,
    :class_name  => "Place",
    :join_table  => "favourite_places",
    :foreign_key => "course_department_id",
    :association_foreign_key => "place_id"

	validates_presence_of :code, :message => "[Kod Bahagian Perlu Diisi]"
	validates_uniqueness_of :code, :on => :create, :message  => "[Kod Bahagian Sudah Wujud]"
	
  validates_length_of :code,	:maximum =>5,
    :message => "tidak melebihi 5 aksara."
										
	validates_length_of :description,	:maximum =>100,
    :message => "tidak melebihi 100 aksara."
end

app/controllers/course_departments_controller.rb
# -*- encoding : utf-8 -*-
class CourseDepartmentsController < ApplicationController
  layout "standard-layout"
  def index
    list
    render :action => 'list'
  end

  def list
    @course_departments = CourseDepartment.paginate(:per_page => 10, :page => params[:page])
#    @course_department_pages, @course_departments = paginate :course_departments, :per_page => 10
  end

  def show
    @course_department = CourseDepartment.find(params[:id])
  end

  def new
    @course_department = CourseDepartment.new
  end

  def create
    @course_department = CourseDepartment.new(params[:course_department])
    if @course_department.save
      flash[:notice] = 'CourseDepartment was successfully created.'
      redirect_to :action => 'list'
    else
      render :action => 'new'
    end
  end

  def edit
    @course_department = CourseDepartment.find(params[:id])
  end

  def update
    @course_department = CourseDepartment.find(params[:id])
    if @course_department.update_attributes(params[:course_department])
      flash[:notice] = 'CourseDepartment was successfully updated.'
      redirect_to :action => 'show', :id => @course_department
    else
      render :action => 'edit'
    end
  end

  def destroy
    CourseDepartment.find(params[:id]).destroy
    redirect_to :action => 'list'
  end
end

app/views/course_departments/_form.html.erb
<div align="center"><%= show_error_messages(@course_department) %></div>

<!--[form:course_department]-->
<table width="95%" border="0" align="center" cellpadding="3" cellspacing="1" bgcolor="#eeeeee">
<tr>
	<td align=right><b>Kod Bahagian :</b></td>
	<td><%= text_field 'course_department', 'code', :size => 5, :maxlength => 5  %></td>	
</tr>
<tr>
	<td align=right><b>Keterangan :</b></td>
	<td><%= text_field 'course_department', 'description', :size => 30, :maxlength => 250  %></td>	
</tr>
</table>
<!--[eoform:course_department]-->

app/views/course_departments/edit.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
  <tr>
    <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">KEMASKINI BAHAGIAN</font></th>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th>
      <%= link_to 'Lihat', :action => 'show', :id => @course_department %> |
      <a href="javascript: history.back()">Kembali</a>
    </th>
  </tr>
</table>
<BR>


<%=form_for(@course_department) do |f| %>
  <%= render :partial => 'form' %>
  <BR>
  <div align=center>
    <%= submit_tag 'Edit' %>
  </div>
<% end %>

app/views/course_departments/list.html.erb
<script src="/javascripts/popupmenu/isohunt.js" type="text/javascript"></script>

<script src="/javascripts/popupmenu/dw_viewport.js" type="text/javascript"></script>
<script type="text/javascript">
  /*************************************************************************
  This code is from Dynamic Web Coding at http://www.dyn-web.com/
  Copyright 2003 by Sharon Paine 
  See Terms of Use at http://www.dyn-web.com/bus/terms.html
  regarding conditions under which you may use this code.
  This notice must be retained in the code as is!
   *************************************************************************/

  var menuLayers = {
    timer: null,
    activeMenuID: null,
    offX: 4,   // horizontal offset
    offY: 6,   // vertical offset

    show: function(id, controller, objid, objname, e) {
      var mnu = document.getElementById? document.getElementById(id): null;
      if (!mnu) return;
      this.activeMenuID = id;
      if ( mnu.onmouseout == null ) mnu.onmouseout = this.mouseoutCheck;
      if ( mnu.onmouseover == null ) mnu.onmouseover = this.clearTimer;
      viewport.getAll();

      //objid = controller + "/" + action + "/" + objid

      document.getElementById('popmenu').innerHTML = "<ul>" +
        //                                               "<li><a href=\""  + controller + "/new/" + objid + "\">&nbsp;&nbsp;New</a>" +
      "<li><a href=\""  + controller + "/" + objid + "/edit\">&nbsp;&nbsp;Kemaskini</a>" +
        "<li><a rel=\"nofollow\" data-method=\"delete\" data-confirm = \"Adakah anda pasti untuk padam " + objname + "?\" href= \""+ controller + "/" + objid+"\" >&nbsp;&nbsp;Padam</a>" +
        //"<li><a href=\"javascript: confirmAndGo('"  + controller + "/destroy/" + objid + "' , '" + objname + "')\">&nbsp;&nbsp;Padam</a>" +
        "</ul>"
      this.position(mnu,e);
    },
  
    hide: function() {
      this.clearTimer();
      if (this.activeMenuID && document.getElementById)
        this.timer = setTimeout("document.getElementById('"+menuLayers.activeMenuID+"').style.visibility = 'hidden'", 200);
    },
  
    position: function(mnu, e) {
      var x = e.pageX? e.pageX: e.clientX + viewport.scrollX;
      var y = e.pageY? e.pageY: e.clientY + viewport.scrollY;
    
      if ( x + mnu.offsetWidth + this.offX > viewport.width + viewport.scrollX )
        x = x - mnu.offsetWidth - this.offX;
      else x = x + this.offX;
  
      if ( y + mnu.offsetHeight + this.offY > viewport.height + viewport.scrollY )
        y = ( y - mnu.offsetHeight - this.offY > viewport.scrollY )? y - mnu.offsetHeight - this.offY : viewport.height + viewport.scrollY - mnu.offsetHeight;
      else y = y + this.offY;
    
      mnu.style.left = x + "px"; mnu.style.top = y + "px";
      this.timer = setTimeout("document.getElementById('" + menuLayers.activeMenuID + "').style.visibility = 'visible'", 200);
    },
  
    mouseoutCheck: function(e) {
      e = e? e: window.event;
      // is element moused into contained by menu? or is it menu (ul or li or a to menu div)?
      var mnu = document.getElementById(menuLayers.activeMenuID);
      var toEl = e.relatedTarget? e.relatedTarget: e.toElement;
      if ( mnu != toEl && !menuLayers.contained(toEl, mnu) ) menuLayers.hide();
    },
  
    // returns true of oNode is contained by oCont (container)
    contained: function(oNode, oCont) {
      if (!oNode) return; // in case alt-tab away while hovering (prevent error)
      while ( oNode = oNode.parentNode )
        if ( oNode == oCont ) return true;
      return false;
    },

    clearTimer: function() {
      if (menuLayers.timer) clearTimeout(menuLayers.timer);
    }
  
  }
</script>

<script>
  function confirmAndGo(url, objname) {
    if (confirm("Are you sure to delete " + objname + "?")) {
      location = url
    }
	
  }
</script>


<form action="/course_departments/list">
  <table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
    <tr> 
      <td width="86%" height="21" align="center" bgcolor="#999999"><b><font color="#FFFFFF">SENARAI BAHAGIAN</font></b></td>
    </tr>
  </table>
  <br>

  <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center">

        <a href="/course_departments/new"><u>Tambah bahagian</u></a>
      </td>
    </tr>
  </table>
  <br>

  <table width="85%" border="0" align="center" cellpadding="2" cellspacing="1" bgcolor="#777777">
    <tr bgcolor="#999999" id="pisang" onclick="//servOC(20,'/course/show/3','#999999')">
      <td width="2%" valign="top" id="name20"><font color="#FFFFFF">&nbsp;<strong>Bil</strong></font></td>
      <td width="25%" align="center"><font color="#FFFFFF">&nbsp;<strong>Kod Bahagian</strong></font></td>
      <td width="" align="center"><font color="#FFFFFF">&nbsp;<strong>Keterangan</strong></font></td>
    </tr>

    <tr style="display: none;" id="ihtr20"><td colspan="7" bgcolor="#ececd9">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
          <tbody><tr><td width="10"></td><td style="border: 3px solid rgb(0, 51, 102);">
                <iframe id="ihif20" frameborder="0" width="100%"></iframe>
              </td></tr>
          </tbody>
        </table></td></tr>
    <% @course_departments.each_with_index do |cd , i|  %>
      <tr bgcolor="<%=cycle("#CCCCFF","#FFFFFF")%>" onmouseover="this.style.background='#FFFFCC'" onmouseout="this.style.background='<%=cycle("#CCCCFF","#FFFFFF")%>'"
          onmousedown="menuLayers.show('popmenu', '/course_departments', '<%=h cd.id %>', '<%= cd.code %>', event)" >
        <td><%= i.to_s %>.</td>
        <td><%= cd.code %></td>
        <td align=left>&nbsp;<%=h cd.description %></td>
      </tr>

    <% end %>
  </table>
</form>
<br />

app/views/course_departments/new.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
  <tr>
    <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">TAMBAH BAHAGIAN</font></th>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th>
      <a href="javascript: history.back()">Kembali</a>
    </th>
  </tr>
</table>
<br />
<%=form_for(@course_department) do |f| %>
  <%= render :partial => 'form' %>
  <br />
  <div align=center>
    <%= submit_tag "Simpan" %>
  </div>
<% end %>

app/views/course_departments/show.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
  <tr>
    <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">MAKLUMAT BAHAGIAN</font></th>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th>
      <%= link_to 'Edit', edit_course_department_path(@course_department) %> |
      <a href="javascript: history.back()">Kembali</a>
    </th>
  </tr>
</table>
<BR>
<table width="95%" border="0" align="center" cellpadding="3" cellspacing="2" bgcolor="#eeeeee">
  <tr>
    <td align=right width=30%><b>Kod Bahagian :</b></td>
    <td><%=h @course_department.code %></td>
  </tr>
  <tr>
    <td align=right><b>Keterangan :</b></td>
    <td><%=h @course_department.description %></td>
  </tr>
</table>