config/routes.rb
  resources :signatures do
    get 'new_popup'
    get 'edit_popup'
    put 'update_popup'
    get 'show_popup'
    get 'destroy'
    collection do
      post 'create_popup'
      get 'list_popup'
      get 'new_popup'
    end
  end

  match '/trainer/:course_implementation_id/edit_surat_lantik_all' => 'trainer#edit_surat_lantik_all', :via => [:get]
  match '/trainer/:course_implementation_id/edit_surat_lantik' => 'trainer#edit_surat_lantik', :via => [:post]
  match '/trainer/:course_implementation_id/cetak_surat_lantik_all' => 'trainer#cetak_surat_lantik_all', :via => [:post]
  match '/trainer/:course_implementation_id/cetak_surat_lantik_all' => 'trainer#cetak_surat_lantik_all', :via => [:put]
  match '/trainer/:course_implementation_id/cetak_surat_lantik' => 'trainer#cetak_surat_lantik', :via => [:post]
  match '/trainer/:course_implementation_id/cetak_surat_lantik' => 'trainer#cetak_surat_lantik', :via => [:put]
  resources :trainer do
    get 'collect'
    get 'release'
    post 'offer'
    get 'offer'
    get 'eval'
    get 'destroy'
    collection do
      get 'offer_all'
      get 'list'
      get 'search'
      get 'claim_payment_index'
      post 'claim_payment_sent'
      post 'search_by_name'
      post 'search_by_ic'
      post 'search_by_phone'
      post 'search_by_expertise'
      post 'search_by_state'
      post 'offer'
    end
  end

  resources :finances do
    collection do
      get 'claim_payment_list'
      get 'search_claim_payment'
      post 'claim_payment_approve'
    end
  end

  resources :report_tables do
    collection do
      get 'general_achievement'
      get 'application_and_attendance'
      get 'peserta_jantina'
      get 'summary_group_ptg_ptd'
      get 'summary_group_jupem'
      get 'peserta_mengikut_jabatan'
      get 'trainer_by_department'
      get 'teach_hour_by_department'
      get 'students_feedback'
      get 'summary_group_jkptg'
      get 'payment_by_department'
      get 'trainer_average_score'
    end
  end

  resources :staffs do
    collection do
      get 'list'
      get 'search'
      post 'search_by_name'
      post 'search_by_phone'
      post 'search_by_dept'
      post 'new_but_staff_already_exist'
      post 'create_but_staff_already_exist'
    end
  end

  resources :report do
    collection do
      get 'list'
      get 'kursus_online'
      get 'kursus_semasa'
      get 'ringkasan_ujian'
    end
  end

  resources :laporan do
    collection do
      get 'audit_trail'
      get 'penilaian_penyelarasan'
      get 'list_laporan'
      get 'pencapaian_ujian_bidang'
      get 'mohon_espek'
      get 'statistik_kursus_tarikh'
      get 'pencapaian_ujian'
      get 'penilaian_penceramah'
      get 'penilaian_kemudahan'
      get 'penilaian_isi_kandungan'
      get 'senarai_ulasan'
      get 'kutipan_yuran'
      get 'kutipan_yuran_bhg'
      post 'sp_create'
      put 'sp_update'
    end
    member do
      get 'status_perlaksanaan'
    end
  end

  resources :reservations do
    collection do
      get 'list'
      get 'listp'
      get 'destroy/:id', action: :destroy
    end
    member do
      get 'new_popup'
      get 'edit_sah'
      get 'show_popup'
      get 'trainer_book'
      post 'trainer_book_create'
      get 'show_trainer_book'
      get 'edit_sah'
      post 'update_sah'
      get 'detail'
    end
  end

  resources :notifications do
    collection do
      get 'list'
      get 'report'
      get 'senaraibilik'
      get 'jadual_bilik_kuliah'
      get 'listp'
      get 'urushubung'
      post 'create_security_contact'
    end
    member do
      get 'detail'
      delete 'delete_security_contact'
      put 'approve'
    end
  end
  match '/hostels/list_sudah_checkin/:id' => 'hostels#list_sudah_checkin', :via => [:get]
  match '/hostels/iwannachkin/:id' => 'hostels#iwannachkin', :via => [:get]
  match '/hostels/showchkin/:id' => 'hostels#showchkin', :via => [:get]
  match '/hostels/:id/change_room' => 'hostels#change_room', :via => [:get]
  resources :hostels do
    collection do
      get 'list'
      get 'new_penghuni'
      post 'create_penghuni'
      get 'chkin_by_course'
      get 'find_checkout'
      get 'list_tutup'
      get 'find_guest'
      get 'rekod_guna_bilik'
      get 'blank'
      get 'lihat'
      get 'find_to_checkin'
      get 'list_active_course'
      get 'find_guest_result'
    end
    member do
      get 'iwannarent'
      get 'iverent'
      get 'showrent'
      get 'showchkin'
      get 'change_room_rent'
      get 'course_sankasha_ichiran'
      get 'cetak_list_checkin'
      get 'course_trainer_list'
      get 'iwannachkin'
      post 'ivedonechkin'
      get 'cetak_list_trainer_checkin'
    end
  end
  resources :quizzes do
    collection do
      get 'list'
      post 'hozon'
      get 'destroy/:id', action: :destroy
    end
    member do
      get 'shiken_ichiran'
      get 'shinki'
      get 'copy_shiken_ichiran'
      put 'simpan_copy_shiken_ichiran'
    end
  end

  match '/course_management/override_kelayakan/:id' => 'course_management#override_kelayakan', :via => [:post]
  match '/course_management/cetak_tempahan_iso/:id' => 'course_management#cetak_tempahan_iso', :via => [:post]
  match '/course_management/hantar_tempahan/:id' => 'course_management#hantar_tempahan', :via => [:post]
  match '/course_management/maklumat_kehadiran/:id' => 'course_management#maklumat_kehadiran', :via => [:get]
  match '/course_management/set_paparan_sijil/:id' => 'course_management#set_paparan_sijil', :via => [:post]
  match '/course_management/edit_surat_pengesahan/:id' => 'course_management#edit_surat_pengesahan', :via => [:post]
  match '/course_management/edit_surat_takhadir/:id' => 'course_management#edit_surat_takhadir', :via => [:post]
  match '/course_management/rujukan_kami/:id' => 'course_management#rujukan_kami', :via => [:get]
  match '/course_management/edit_tempah_sijil' => 'course_management#edit_tempah_sijil', :via => [:post]
  match '/course_management/cetak_sijil' => 'course_management#cetak_sijil', :via => [:post]
  match 'course_management/evaluation/:course_management_id' => 'course_management#evaluation', :via => [:get]
  match 'course_management/p_evaluation/:course_management_id' => 'course_management#p_evaluation', :via => [:get]
  match '/course_management/:course_management_id/p_evaluation' => 'course_management#p_evaluation', :via => [:get]
  match 'course_management/register/:id' => 'course_management#register', :via => [:get]
  resources :course_management do
    get 'evaluation_done'
    collection do
      get 'select_course(/:role)', action: :select_course
      get 'sijil_select_course'
      get 'evaluated_courses'
      get 'register'
      get 'ichiran'
      get 'yuran'
      get 'attendance'
      get 'certificate'
      get 'evaluation'
      get 'p_evaluation'
      get 'enroll_selected'
      get 'cetak_sijil'
      get 'surat_pengesahan'
      get 'surat_takhadir'
      post 'isi_markah'
      get 'make_payment'
      get 'cetak_yuran'
    end
    member do
      put 'jana_surat_pengesahan_pdf'
      put 'jana_surat_takhadir_pdf'
      get 'update_polisi_sijil'
      get 'new_polisi_sijil'
      get 'enroll_selected'
      get 'evaluation_kelompok'
      get 'jana_kelayakan'
      get 'tempah_sijil'
      get 'tempah_sijil_iso'
      get 'new_tarikh_sesi'
      post 'new_sesi'
      post 'edit_sesi'
      get 'create_sesi'
      get 'update_sesi'
      get 'new_tarikh_sesi'
      get 'new_cetak_kehadiran'
      get 'new_catat_kehadiran'
      get 'kehadiran_manual'
      post 'masuk_data_kehadiran'
      get 'cetak_p_evaluation_iso'
      get 'cetak_p_evaluation'
      get 'list_signature'
      get 'surat_takhadir'
      get 'surat_pengesahan'
      get 'certificate'
      get 'attendance'
      get 'yuran'
      get 'register'
    end
  end
  match '/course_applications/all/:course_application_id' => 'course_applications#all', :via => [:get]
  match '/course_applications/unprocessed/:id' => 'course_applications#unprocessed', :via => [:get]
  match '/course_applications/hadir/:id' => 'course_applications#hadir', :via => [:get]
  match '/course_applications/accepted/:id' => 'course_applications#accepted', :via => [:get]
  match '/course_applications/rejected/:id' => 'course_applications#rejected', :via => [:get]
  match '/course_applications/confirmed/:id' => 'course_applications#confirmed', :via => [:get]
  match '/course_applications/confirmednot/:id' => 'course_applications#confirmednot', :via => [:get]
  match '/course_applications/norespon/:id' => 'course_applications#norespon', :via => [:get]
  match '/course_applications/takhadir/:id' => 'course_applications#takhadir', :via => [:get]
  match '/course_applications/edit_surat_tawaran' => 'course_applications#edit_surat_tawaran', :via => [:get]
  match '/course_applications/sah_hadir_selected' => 'course_applications#sah_hadir_selected', :via => [:get]
  match '/course_applications/cetak_pemohon/:id' => 'course_applications#cetak_pemohon', :via => [:get]
  match '/course_applications/cetak_pemohon_semua/:id' => 'course_applications#cetak_pemohon_semua', :via => [:get]
  match '/course_applications/konaitokimeta' => 'course_applications#konaitokimeta', :via => [:get]
  match '/course_applications/new_for_logged_in_user/:id' => 'course_applications#new_for_logged_in_user', :via => [:get]
  match '/course_applications/create_for_logged_in_user/:id' => 'course_applications#create_for_logged_in_user', :via => [:post]
  match '/course_applications/create_but_peserta_already_exist' => 'course_applications#create_but_peserta_already_exist', :via => [:post]
  match '/course_applications/new_but_peserta_already_exist' => 'course_applications#new_but_peserta_already_exist', :via => [:get]
  match '/course_applications/user_daftar/:id' => 'course_applications#user_daftar', :via => [:get]
  match '/course_applications/new/:id' => 'course_applications#new', :via => [:get]

app/models/notification.rb
class Notification < ActiveRecord::Base
  set_primary_key :id
  belongs_to :course_implementation
  belongs_to :course
  belongs_to :course_location
  belongs_to :profile
  belongs_to :user
end

app/helpers/notifications_helper.rb
# -*- encoding : utf-8 -*-
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<!--[form:notification]-->
  <table width="85%" border="0" align="center" bgcolor="#FFFFFF">
  <tr bgcolor="#000000">
    	<td colspan="4" align="LEFT" bgcolor="#999999"><b><font color="#FFFFFF">MAKLUMAT PEMOHON </font></b></td>
    </tr>
  <tr>
    <td align="left"><b>Nama Pemohon</b></td>
    <td colspan=3>:&nbsp;<%= nof{session[:user].profile.name}%></td>
  </tr>
<%
employment = Employment.find_by_profile_id(session[:user].profile_id)
%>
  <tr>
    <td align="left"><b>Bahagian</b></td>
    <td colspan=3>:&nbsp;<%= nof{employment.unit.upcase}%></td>
  </tr>
  <tr>
    <td align="left"><b>Tujuan</b></td>
    <td colspan=3>:&nbsp;<%= nof{@course_implementation.course.name}%></td>
  </tr>
  <tr>
    <td align="left"><b>No. Samb.</b></td>
    <td colspan=3>:&nbsp;</td>
    <td><%= hidden_field 'notification', 'trainer_total', :value=>0 %>
    <%= hidden_field 'notification', 'date_plan_start', :value=> @course_implementation.date_plan_start %>
    <%= hidden_field 'notification', 'date_plan_end', :value=> @course_implementation.date_plan_end %>
    <%= hidden_field 'notification', 'course_implementation_id', :value=> @course_implementation.id %>
    <%= hidden_field 'notification', 'course_id', :value=> @course_implementation.course.id %>
	<%= hidden_field 'notification', 'user_id', :value=>session[:user].id %>
	<%= hidden_field 'notification', 'profile_id', :value=>session[:user].profile_id %></td>
  </tr>
	<tr>
		<td>&nbsp;</td>
		</tr>
   <!--tr>
    <td align="right"><b>Tarikh Kursus: </b></td>
    <td>&nbsp;<%= nof{@course_implementation.date_plan_start.to_formatted_s(:my_format_4)} %> hingga
   			<%=
	         if !@course_implementation.date_end
			 	@course_implementation.date_plan_end.to_formatted_s(:my_format_4)
			 else
			 	@course_implementation.date_end.to_formatted_s(:my_format_4)
			 end
				-%>    </td>
  </tr>
   <tr>
    <td align="right"><b>Tarikh dan masa check-in: </b></td>
    <td>&nbsp;<%= nof{@course_implementation.check_in.to_formatted_s(:my_format_7)} %></td>
	</tr>
	<tr>
    <td align="right"><b>Tarikh dan masa check-out: </b></td>
    <td>&nbsp;<%= nof{@course_implementation.check_out.to_formatted_s(:my_format_7)} %></td>
  </tr-->
  <!--tr>
    <td align="right"><b>Bilangan Peserta Kursus: </b></td>
    <td><%= text_field 'notification', 'male_total', :value=>@male.size, :maxlength=>4, :size=>4  %></td>
  </tr>
  <tr>
    <td align="right"><b>Bilangan Penceramah Kursus: </b></td>
  </tr-->
  <tr bgcolor="000000">
   	<td colspan="4" align="LEFT" bgcolor="#999999"><b><font color="#FFFFFF">MAKLUMAT BILIK YANG DIPOHON</font></b></td>
   </tr>
	<tr>
		<td>&nbsp;</td>
		</tr>
	<tr>
    <td align="CENTER" colspan="4">
	   <fieldset style="width:90%">
	    <table width="95%" align="center" border=0>
<%
	  	  ds = @course_implementation.date_start
		  de = @course_implementation.date_end
		  howlong = (de-ds).to_i+1
		  @options = Array.new;
		  @days = Array.new
		  howlong.times do |i|
		  	b = ds+i
			c = dmy(b,"-","/");
		  	@options.push([c,ds+i]);
		  end
		  @days = @options;
		
		  @days.each { |day|
%>
			<tr>
				<td width="100" align="right"><%=day[0]%>:</td>
				<td>
				<select id="hari[<%=day[1]%>][facility_id]" name="hari[<%=day[1]%>][facility_id]" onchange="checkField()";>
					<option value=''>Sila Pilih</option>
					<% @facilities.each do |facility| %>
					<option value="<%= facility.id %>"
					<%= ' selected' if facility.id == @notification.facility_id %>> <%= facility.facility_type.description %>-<%= facility.name %> </option>
					<% end %>  
				</select>	
				</td>
			</tr>
<%        } %>
		</table>
	   </fieldset>	  </td>
  </tr>
  <tr>
	<td align="left">Tarikh Permohonan</td>
	<td>:&nbsp;
      <input id="day_check_in" type=text name="day_check_in" value="<%=@day%>" size=2 maxlength=2 >
-
  <input id="month_check_in" type=text name="month_check_in" value="<%=@month%>" size=2 maxlength=2 >
-
<input id="year_check_in" type=text name="year_check_in" value="<%=@year%>" size=4 maxlength=4></td>
    </tr>
   <tr bgcolor="000000">
     <td colspan="4" align="CENTER" bgcolor="#FFFFFF">&nbsp;</td>
   </tr>
   <!--tr bgcolor="000000">
    	<td colspan="4" align="LEFT" bgcolor="#999999"><b><font color="#FFFFFF">UNTUK KEGUNAAN SEKSYEN KESELAMATAN </font></b></td>
    </tr>
    <tr>
    <td colspan="4" align="left">Permohonan tuan/puan sepertimana yang dipohon telah :</td>
  </tr>
	<tr>
    <td align="CENTER"></td>

        <%
        checked_0 = checked_1 = ""
        checked_1 = "checked" if @notification.status == "1"
        checked_0 = "checked" if @notification.status == "0"
        %>
    <td><input name="notification[status]" type="radio" value="1" disabled="disabled"<%=checked_1%>>Diluluskan
    <input name="notification[status]" type="radio" value="0" disabled="disabled"<%=checked_0%>>Ditolak
        </td>
  </tr>
    <tr>
    <td align="left">Cadangan bilik lain</td>
    <td colspan="3"><%= text_field 'notification', 'remark', :maxlength=>0, :size=>50, :disabled=>true %></td>
  </tr--!>
      <tr>
    <td colspan="4" align="left"><%=render :partial => 'pegawai_keselamatan'%></td>
  </tr>
  <!--tr>
	<td align="left">Tarikh Kelulusan</td>
	<td>:&nbsp;
      <input id="day_approve" type=text name="day_approve" value="" size=2 maxlength=2 disabled=disabled>
-
  <input id="month_approve" type=text name="month_approve" value="" size=2 maxlength=2 disabled=disabled>
-
<input id="year_approve" type=text name="year_approve" value="" size=4 maxlength=4 disabled=disabled></td>
    </tr--!>
</table>
</BR>
<!--[eoform:notification]-->

app/views/notifications/_pegawai_keselamatan.html.erb
<small><b>Sila nyatakan persetujuan dengan menelefon Seksyen Keselamatan di samb 3059/3030/3034 (En. Mohd Fairuszaman/En. Muhd Ikmal Fairuz/En. Mohd Ahmadshah)</b></small>

app/views/notifications/edit.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
    <tr> 
      <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">MAKLUMAN PELAKSANAAN KURSUS KEPADA SEKSYEN KESELAMATAN</font></th>
    </tr>
  </table>
<BR>
	
<%#= start_form_tag :action => 'approve', :id => @notification %>
<%=form_for(@notification, :url => approve_notification_path(:id=>@notification)) do |f|%>
  <%= render :partial => 'form_approve' %>
  <div align="center">
  <%= submit_tag 'Kemaskini' %>
  </div>
<% end %>

app/views/notifications/jadual_bilik_kuliah.html.erb
<h1><%=@facility.name%></h1>
<%@facility_reservations.each do |facility_reservation|%>
	<%=facility_reservation.date_from%> <br/>
	<%end%>

app/views/notifications/new.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
  <tr>
    <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">MAKLUMAN PELAKSANAAN KURSUS KEPADA SEKSYEN KESELAMATAN</font></th>
  </tr>
</table>
<BR>
<% if !@check %>
  <%=form_for(@notification) do |f|%>
  <%= render :partial => 'form' %>
  <div align="center">
    <%= submit_tag "Simpan" %>
  </div>
  <% end %>
<% else %>
<%= form_for(@notification, :url => notification_path(:id => @check), :html => {:method => :put}) do |f| %>
  <%#= start_form_tag :action => 'update',  %>
  <%= render :partial => 'form_edit' %>
  <div align="center">
    <%= submit_tag 'Kemaskini' %>
  </div>
  <%end %>
<% end %>

app/views/notifications/report.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
    <tr> 
      <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">LAPORAN STATISTIK PENGGUNAAN BILIK KULIAH</font></th>
    </tr>
  </table>
<BR>

  <table width="85%" border="<%=list_border%>" align="center" cellpadding="<%=list_cellpadding%>" cellspacing="<%=list_cellspacing%>" bgcolor="<%=list_bgcolor%>">
	   <tr bgcolor="000000">
	    	<td colspan="7" align="CENTER" bgcolor="#999999"><b><font color="#FFFFFF">Senarai Bilik </font></b></td>
	    </tr>
      <tr bgcolor="#999999">
  <td width="5%" align="CENTER"><b><font color="#FFFFFF">Bil</font></b></td>
  <td width="25%" align="CENTER"><b><font color="#FFFFFF">Nama Bilik</font></b></td>
  <td width="10%" align="CENTER"><b><font color="#FFFFFF">Kod</font></b></td>
  <td width="10%" align="CENTER"><b><font color="#FFFFFF">Lokasi</font></b></td>
  <td width="15%" align="CENTER"><b><font color="#FFFFFF">Kekerapan(Hari)</font></b></td>
   </tr>
<%
i = 0;
fr = 0;
even = true;

for facility in @facilities
        i = i + 1
        bgclr = "#CCCCFF" if (even == true)
        bgclr = "#FFFFFF" if (even == false)
        even = !even
	fr = FacilityReservation.where(:facility_id => "=#{facility.id}").count
%>
<tr bgcolor="<%=bgclr%>" class="list">
        <td align=left valign=top><%= i.to_s %></td>
        <td align=left valign=top><%=h nof{facility.name} %></td>
        <td align=left valign=top><%=h nof{facility.code.upcase} %></td>
        <td align=left valign=top><%=h nof{facility.facility_type.description} %></td>
        <td align=center valign=top><%=h fr %></td>
        </tr>
 <% end %>
</table>  
<br />

app/views/notifications/senaraibilik.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="95%" align="center">
  <tr>
    <th width="85%" height="20" bgcolor="#999999">
      <font color="#FFFFFF">LAPORAN STATISTIK PENGGUNAAN BILIK KULIAH</font></th>
  </tr>
</table>
<BR>

<table width="85%" border="<%=list_border%>" align="center" cellpadding="<%=list_cellpadding%>" cellspacing="<%=list_cellspacing%>" bgcolor="<%=list_bgcolor%>">
  <tr bgcolor="000000">
    <td colspan="7" align="CENTER" bgcolor="#999999"><b><font color="#FFFFFF">Senarai Bilik </font></b></td>
  </tr>
  <tr bgcolor="#999999">
    <td width="5%" align="CENTER"><b><font color="#FFFFFF">Bil</font></b></td>
    <td width="25%" align="CENTER"><b><font color="#FFFFFF">Nama Bilik</font></b></td>
    <td width="10%" align="CENTER"><b><font color="#FFFFFF">Kod</font></b></td>
    <td width="10%" align="CENTER"><b><font color="#FFFFFF">Lokasi</font></b></td>
  </tr>
  <%
  i = 0;
  fr = 0;
  even = true;

  for facility in @facilities
    i = i + 1
    bgclr = "#CCCCFF" if (even == true)
    bgclr = "#FFFFFF" if (even == false)
    even = !even
    fr = FacilityReservation.where(:facility_id => "=#{facility.id}").count
  %>
    <tr bgcolor="<%=bgclr%>" class="list">
      <td align=left valign=top><%= i.to_s %></td>
      <td align=left valign=top><%=link_to nof{facility.name}, :controller => 'notifications',:action => 'jadual_bilik_kuliah', :id => facility.id %></td>
      <td align=left valign=top><%=h nof{facility.code.upcase} %></td>
      <td align=left valign=top><%=h nof{facility.facility_type.description} %></td>
    </tr>
  <% end %>
</table>  
<br />

app/views/notifications/show.html.erb
<% for column in Notification.content_columns %>
<p>
  <b><%= column.human_name %>:</b> <%=h @notification.send(column.name) %>
</p>
<% end %>

<%= link_to 'Edit', :action => 'edit', :id => @notification %> |
<%= link_to 'Back', :action => 'list' %>

app/views/notifications/urushubung.html.erb
<%=form_for(@security_contact, :url => create_security_contact_notifications_path(:id => @security_contact.id)) do |f|%>
<%#= start_form_tag :action => 'create_security_contact', :id => @security_contact.id unless @security_contact.nil? %>
<table width="85%" border="0" align="center" bgcolor="#FFFFFF">
  <tr bgcolor="#000000">
    <td colspan="4" align="LEFT" bgcolor="#999999"><b><font color="#FFFFFF">TAMBAH MAKLUMAT KESELAMATAN</font></b></td>
  </tr>
  <tr>
    <td align="left" width="14%"><b>Nama </b></td>
    <td colspan=3>:&nbsp;<%=text_field :security_contact, :name%></td>
  </tr>

  <tr>
    <td align="left"><b>Email</b></td>
    <td colspan=3>:&nbsp;<%=text_field :security_contact, :email%></td>
  </tr>
  <tr>
    <td align="left"><b>No. Samb.</b></td>
    <td colspan=3>:&nbsp;<%=text_field :security_contact, :extension%></td>
  </tr>
  <tr bgcolor="000000">
    <td colspan="4" align="LEFT" bgcolor="#999999">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3" align="center"> <%= submit_tag 'Kemaskini' %>

    </td>
    <td width="66%" align="center">&nbsp;</td>
  </tr>
</table>

<div id="clear"></div>
<table width="85%" border="0" align="center" bgcolor="#FFFFFF">
  <tr bgcolor="#000000">
    <td colspan="4" align="LEFT" bgcolor="#999999"><b><font color="#FFFFFF">SENARAI MAKLUMAT PEGAWAI KESELAMATAN</font></b></td>
  </tr>
  <%@security_contacts.each do |security_contact|%>
    <tr>
      <td align="left" width="14%"><b>Nama </b></td>
      <td colspan=2>:&nbsp;<%=security_contact.name%></td>
      <td><%=link_to 'Delete', 
  delete_security_contact_notification_path(:id => security_contact.id),
  :confirm => 'Are You Sure ?',  :method => :delete %> | <%=link_to 'Edit', :action => 'urushubung', :id => security_contact.id%></td>
    </tr>

    <tr>
      <td align="left"><b>Email</b></td>
      <td colspan=2>:&nbsp;<%=security_contact.email%></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td align="left"><b>No. Samb.</b></td>
      <td colspan=2>:&nbsp;<%=security_contact.extension%></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="4" align="center">&nbsp;</td>
    </tr>
  <%end%>

  <tr bgcolor="000000">
    <td colspan="4" align="LEFT" bgcolor="#999999">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3" align="center">&nbsp;</td>
    <td width="50%" align="center">&nbsp;</td>
  </tr>
</table>

<% end %>